### ISSUE TITLE
Consider providing Add Existing Credentials / Retrieve Credentials / ... etc in Credentials manager

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-visualstudio#193]
Current dialog does not support adding credentials already defined, it can only reset them. If I have a VM with a login/pwd combo I want, I cannot use it. If a login is shared, it means each user needing to use it will have to reset the password.

**Comment by chrsmith** [comment]
@YnR On an internal thread we followed up with the GCE VM folks, and it does not appear to be a way we can do this (at least from the `gcloud` side). I don't know if we can also check the VM directly, because without the machine being domain joined, enabling remote logins, etc. I don't know if we can arbitrarily check if a username is a local Windows account.

So it might seem that the text should read "Create new or OBLITERATE EXISTING". How should we word that? With a giant skull and crossbones warning?

**Comment by YnR** [comment]
I was thinking we should at least allow you to type in an existing username password, if you already have one you set on the machine.

**Comment by ivannaranjo** [comment]
Working on it.

**Comment by ivannaranjo** [comment]
This is now fixed in PR #211
