### ISSUE TITLE
Disable Add Data Connection menu if there is no authorized networks?

### ISSUE THREAD

**Issue by Deren-Liao** [GoogleCloudPlatform/google-cloud-visualstudio#320]
For a first time user, it's quite confusing about what to do to successfully add a data connection. 
(1) We may just disable it if there is no "authorized networks" configured at all.  In this case, it's impossible for adding a SQL connection.
(2) Add help links somewhere that points to instructions about how to enable SQL connection on a developer machine.

**Comment by chrsmith** [comment]
[my two cents]

Could you elaborate on this? By "no authorized networks" do you mean that the user hasn't added a network to their Cloud SQL database instance? So it is unreachable from Visual Studio?

If that is the case, I would recommend adding a warning icon in the UI or something. e.g. "Some Cloud SQL instances are not displayed because they do not have an authorized network. Click here to learn more."

**Comment by Deren-Liao** [comment]
Yes, that's the case.

**Comment by ivannaranjo** [comment]
I don't fully agree with hiding the SQL instances, they should all be present in the list as the user can perform (potentially) other operations on them rather than accessing the data.

The add connection command should show a warning (a prompt to the user) that tells them that they should add authorized networks before proceeding. But the option itself should not be disabled.

Now the extension cannot really provide an option to authorize the developer machine as more often than not they're going to be behind a NAT, router, etc... So the IP address of the dev's machine is going to be a private one and you need the public one. We need to make this explicit in the help.
