### ISSUE TITLE
I want the template to find my project id.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-visualstudio#573]
I created a new GoogleAspNetCoreMvc project.  In the appsettings is this line:
"ProjectId": "YOUR-PROJECT-ID",

I want an IConfigurationProvider that finds and fills this value for me.  It should check:
1.  The current project listed in the file pointed to GOOGLE_APPLICATION_CREDENTIALS.  That file contains the project id.
2.  If running on GCE or GAE, it should check the metadata server.

Then, "ProjectId" can be omitted from appsettings.json entirely.  Of course, the user can specify it there to override.

**Comment by ivannaranjo** [comment]
Looking at my application default credentials it does not contain the project id. I think that was an older version of the auth code. The truth is that getting the project id while running locally is not a trivial matter.

We could help in VS by setting the GOOGLE_CLOUD_PROJECT environment variable to the currently selected one. This environment variable is a standard way (more or less) to discover the current project ID, if set.

As for running on GCE, it already does get the current project ID from the metadata server, but it still fails because it give precedence to the value in the config file, as it is used to override any other source.

We should at least have it there commented, so the user knows to use it if needed.

**Comment by ivannaranjo** [comment]
We can change the behavior of the template so the project id is **not** specified by default. At runtime we can throw if no project id is found, then the user can set up the env vars, or whatever, to allow local debugging.

This behavior change would not affect the app running on production of course.

**Comment by ILMTitan** [comment]
Within my template project cleanup I inverted the behavior of the Project ID check. It now checks the metadata servers first, and falls back to the configured ID if that fails. I also added a wizard so you can specify your backup project id, allowing the templates to run locally from the moment they are created on.
